version: '3'
services:
  snake_app_name:
    build: src
    hostname: snake_app_name
    container_name: snake_app_name
    env_file: 'src/template.env'
    environment:
      APP_PORT: ${APP_PORT:-8080}
    ports:
      - "${HOST_PORT:-8080}:${APP_PORT:-8080}"